---

services:
    www:
        build: .
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html/
        links:
            - db
        networks:
            - default
    db:
        image: mysql:8.0
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: prabhat
            MYSQL_USER: prabhat
            MYSQL_PASSWORD: prabhat@10
            MYSQL_ROOT_PASSWORD: prabhat@10
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - persistent:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - db:db
        ports:
            - 82:80
        environment:
            MYSQL_USER: prabhat
            MYSQL_PASSWORD: prabhat@10
            MYSQL_ROOT_PASSWORD: prabhat@10
volumes:
    persistent: